services:
  postgres:
    image: postgres:latest
    container_name: lab-2-tools-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - configuration-service-network
  
  configuration-service:
    image: ghcr.io/is-csms-y27/lab-2-tools:master
    platform: linux/amd64
    container_name: configuration-service
    networks:
      - configuration-service-network
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      Persistence__Postgres__Host: postgres

  task31-scenario-db:
    image: postgres:16
    container_name: task31-scenario-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task31_scenario
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - configuration-service-network

networks:
  configuration-service-network:
    driver: bridge
